name: PHI group
url: https://phi-group.github.io/

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: pi
    name: Principal Investigator
  - key: faculty
    name: Faculty Members
  - key: postdoc
    name: Postdoc Fellows
  - key: grad
    name: Graduate Students
  - key: visit
    name: Visitors
  #- key: alum
  #  name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true
  publications:
    output: true
  resources:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Projects
    link: /projects.html
  - title: Publications
    link: /publications.html
  - title: Resources
    link: /resources.html
